# Generated by Django 5.2.4 on 2025-09-04 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BlogHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_line', models.CharField(default='Don’t Just Gain info', max_length=120)),
                ('highlight_text', models.CharField(default='Build Knowledge', max_length=50)),
                ('subtext', models.TextField(default="Whether you’re a new investor or a market expert, we’ve got something for everyone at the <span class='neon'>TRACO</span> blog")),
                ('image', models.ImageField(upload_to='blogs/hero/')),
                ('oval_width', models.PositiveIntegerField(default=260)),
                ('oval_height', models.PositiveIntegerField(default=320)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blogs/posts/')),
                ('overlay_title', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=140)),
                ('read_minutes', models.PositiveIntegerField(default=5)),
                ('published_on', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.blogcategory')),
            ],
            options={
                'ordering': ['-published_on'],
            },
        ),
    ]
