# Generated by Django 5.2.4 on 2025-09-04 19:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_authsideimage_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='partner/features/')),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PartnerPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(upload_to='partner/hero/')),
                ('heading_lead', models.CharField(default='Welcome to the First Step of Becoming a', max_length=120)),
                ('highlight', models.CharField(default='TRACO', max_length=32)),
                ('heading_tail', models.CharField(default='Partner', max_length=32)),
                ('contact_heading', models.CharField(default='Contact us Alternatively , You can Contact Our Business Partner Team', max_length=120)),
                ('phone_label', models.CharField(default='Phone Number', max_length=64)),
                ('phone_value', models.CharField(default='022 982231', max_length=64)),
                ('email_label', models.CharField(default='Email id', max_length=64)),
                ('email_value', models.EmailField(default='businesspartner@tranco.in', max_length=254)),
                ('line1', models.CharField(default='People become partners to earn passive income and grow with a trusted brand.', max_length=200)),
                ('line2', models.CharField(default='They get access to high commissions, marketing support, and long-term business potential.', max_length=220)),
                ('line3', models.CharField(blank=True, default='', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('pincode', models.CharField(max_length=10)),
                ('otp', models.CharField(blank=True, max_length=6)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_apps', to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.partnercity')),
            ],
        ),
    ]
