# Generated by Django 5.2.4 on 2025-09-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_partnercity_partnerfeature_partnerpage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('title_part_left', models.CharField(blank=True, help_text='left part (colored green)', max_length=100)),
                ('title_part_right', models.CharField(blank=True, help_text='right part (colored green)', max_length=100)),
                ('title_highlight', models.CharField(blank=True, help_text='TRACO or main highlight (radial color)', max_length=100)),
                ('subtitle', models.TextField(blank=True, help_text='small paragraph / lines')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='home/features/')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_image', models.ImageField(blank=True, null=True, upload_to='home/hero/')),
                ('right_hero_image', models.ImageField(blank=True, null=True, upload_to='home/hero/')),
                ('line1', models.TextField(default="20 years of industry expertise, we've empowered thousands")),
                ('line2', models.TextField(default='of traders to take control of their financial future. Our platform')),
                ('line3', models.TextField(default='combines proven experience with cutting-edge tools to help')),
                ('line4', models.TextField(default='you trade smarter, faster, and more confidently.')),
                ('line3_highlight_start', models.CharField(blank=True, default='combines', max_length=60)),
                ('line3_highlight_end', models.CharField(blank=True, default='tools', max_length=60)),
                ('line4_highlight_start', models.CharField(blank=True, default='you trade smarter,', max_length=60)),
                ('line4_highlight_end', models.CharField(blank=True, default='confidently', max_length=60)),
            ],
        ),
    ]
