# Generated by Django 5.2.4 on 2025-09-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_homefeature_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSectionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.PositiveSmallIntegerField(choices=[(1, '01'), (2, '02'), (3, '03')], unique=True)),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, help_text="Either a path (/blogs/) or a named URL (blogs). First & second cards will link to {% url 'blogs' %} in template.", max_length=255)),
                ('is_center', models.BooleanField(default=False, help_text='Make this the taller neon center card')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers show first (left)')),
            ],
            options={
                'verbose_name': 'Home Section Card',
                'verbose_name_plural': 'Home Section Cards',
                'ordering': ['order', 'serial'],
            },
        ),
    ]
