# Generated by Django 5.2.4 on 2025-09-06 07:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_homesectioncard'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowItWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='How it Works?', max_length=120)),
                ('background', models.ImageField(blank=True, help_text='Optional subtle background or pattern (not required)', null=True, upload_to='how/bg/')),
            ],
        ),
        migrations.CreateModel(
            name='HowItWorksStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(help_text='Short paragraph shown under the title')),
                ('icon', models.ImageField(upload_to='how/icons/')),
                ('accent_color', models.CharField(default='#a7f542', help_text='Hex color (e.g. #a7f542)', max_length=7)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.howitworks')),
            ],
            options={
                'verbose_name': 'How it Works step',
                'ordering': ('order',),
            },
        ),
    ]
