# Generated by Django 5.2.4 on 2025-09-06 08:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_howitworks_howitworksstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.PositiveSmallIntegerField(choices=[(1, 'Column 1'), (2, 'Column 2'), (3, 'Column 3'), (4, 'Column 4'), (5, 'Column 5')], default=1)),
                ('text', models.CharField(max_length=160)),
                ('url', models.CharField(blank=True, help_text='External URL or site path', max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['column', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='footer/')),
                ('logo_alt', models.CharField(blank=True, default='TRACO', max_length=120)),
                ('newsletter_heading', models.CharField(default='Newsletter', max_length=120)),
                ('newsletter_placeholder', models.CharField(default='Enter Your Email', max_length=120)),
                ('newsletter_button_text', models.CharField(default='Subscribe', max_length=60)),
                ('newsletter_subscriber_notify_email', models.EmailField(blank=True, help_text='Email that receives subscription notifications (optional).', max_length=254)),
                ('newsletter_description', models.TextField(blank=True, default="NFT's are Transforming the way Commerce is a Transacted.")),
            ],
            options={
                'verbose_name': 'Footer Settings',
                'verbose_name_plural': 'Footer Settings',
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram')], max_length=30)),
                ('url', models.URLField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
