# Generated by Django 5.2.4 on 2025-09-06 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_footerlink_footersettings_newslettersubscriber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunitySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_before', models.CharField(default='Build a', max_length=120)),
                ('heading_strong', models.CharField(default='Strong', max_length=120)),
                ('heading_after', models.CharField(default='Community', max_length=120)),
                ('line_1', models.CharField(blank=True, default='Join a global network of passionate traders.', max_length=240)),
                ('line_2', models.CharField(blank=True, default='Share strategies, learn from experts, and grow together', max_length=240)),
                ('line_3', models.CharField(blank=True, default='in a supportive, success-driven environment.', max_length=240)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='community/hero/')),
                ('hero_image_alt', models.CharField(blank=True, default='Community Preview', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='community/')),
                ('caption', models.CharField(blank=True, max_length=160)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.communitysection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
