# Generated by Django 5.2.6 on 2025-09-06 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_communitysection_communityimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_small', models.CharField(blank=True, help_text='Keep your money safe text', max_length=120)),
                ('title_line1', models.CharField(blank=True, max_length=160)),
                ('title_line2', models.CharField(blank=True, max_length=160)),
                ('title_line3', models.CharField(blank=True, max_length=160)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('man_image', models.ImageField(blank=True, help_text='Right-side man image (PNG recommended with transparent background if you want overlap).', null=True, upload_to='banners/')),
                ('user_count_text', models.CharField(default='500+', max_length=64)),
                ('user_count_label', models.CharField(default='Realtime Users', max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BannerAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/avatars/')),
                ('alt', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to='core.banner')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Your Trading Journey Started Here....', max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctas', to='core.banner')),
            ],
        ),
    ]
